services:
  mysql:
    image: mysql:8.0
    container_name: ms-user-db
    environment:
      MYSQL_DATABASE: ms-user-db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_user_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_user_data: